/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_safetone_rfid_lib_CommUart */

#ifndef _Included_net_safetone_rfid_lib_CommUart
#define _Included_net_safetone_rfid_lib_CommUart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_safetone_rfid_lib_CommUart
 * Method:    uart_open
 * Signature: (Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_net_safetone_rfid_lib_CommUart_uart_1open
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     net_safetone_rfid_lib_CommUart
 * Method:    uart_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_safetone_rfid_lib_CommUart_uart_1close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
